services:
  - type: web
    name: Appli
    runtime: node
    repo: https://github.com/YacineMeki/blue_print
    region: frankfurt
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString
  
databases:
  - name: cloud-db
    region: frankfurt
    plan: free
    databaseName: cloud
    user: cloud